export const Sectores = [
  { name: 'Agricultura e Agropecuária', id: 1 },
  { name: 'Alimentação e Bebidas', id: 2 },
  { name: 'Tecnologia da Informação e Software', id: 3 },
  { name: 'Saúde e Bem-Estar', id: 4 },
  { name: 'Educação', id: 5 },
  { name: 'Construção Civil', id: 6 },
  { name: 'Energia', id: 7 },
  { name: 'Indústria Automotiva', id: 8 },
  { name: 'Varejo', id: 9 },
  { name: 'Serviços Financeiros', id: 10 },
  { name: 'Telecomunicações', id: 11 },
  { name: 'Transporte e Logística', id: 12 },
  { name: 'Turismo e Hospitalidade', id: 13 },
  { name: 'Meio Ambiente e Sustentabilidade', id: 14 },
  { name: 'Moda e Beleza', id: 15 },
  { name: 'Estética Automotiva', id: 16 },
  { name: 'Offshore e Onshore', id: 17 },
  { name: 'Serviços Gerais', id: 18 },
]
